Add information about RDKit 2024.03.1
rdkit-users-jp/rdkit-users-jp.github.io pull request #5
Opened 2024-08-05 16:05 UTC by ItsukiMaeda

このPull requestはRDKit日本ユーザー会のWebサイトに [RDKit 2024.03.1 のリリースノート](https://github.com/rdkit/rdkit/releases/tag/Release_2024_03_1)の抄訳を追加します。本リリースに関する公式ブログの記事は見当たりませんでした。

2024-08-12 09:07 UTC, n-yoshikawa requested changes
pull requestありがとうございます。いくつか気になる点があったのでコメントしました。

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- アトロピソマーをサポートする最初のバージョンが追加されました。これは将来のリリースで拡張される予定です。
私が調べた限りではatropisomerは「アトロプ異性体」と訳す例の方が多いようでした

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- 立体配座生成のデフォルトを改善するために2つの変更が行われました。EmbedMolecule()関数とEmbedMultipleConfis()関数はデフォルトでETKDGv3を使用するようになり(以前はETKDGV1を使用していました)、配座剪定のためにRMSDを計算する際に重原子のみを考慮するようになりました(以前は水素原子も考慮されていました)。
この文脈だとpruningは「枝刈り」と訳すのが一般的だと思います。 cf. https://future-chem.com/rdkit-conformer/

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- molブロックに由来する原子のラジカル電子数の計算方法が変更されました。`DOUBLET`としてマークされた`[CH]`のようなシステムには、3つのラジカル電子が割り当てられるようになりました。これはSMILESの値と一致しています。
SMILES自体にはラジカル電子数の情報が含まれないので、「SMILESの値」というよりは「SMILESから計算される値」や「SMILESに基づく値」のようにfromのニュアンスを残した訳にしたほうが意味が通りやすいように思います。

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- MolStandardizeのバリデーションクラスは、よりシンプルで一貫性のあるAPIを提供するためにリファクタリングされました。C++の実装では、`MolVSValidations`基底クラスが削除され、`ValidationMethod`に統合されました。その結果、MolVSに関連するサブクラス（つまり、`NoAtomValidation`、`FragmentValidation`、`N
"the validate method replaced run" は直訳すると「validateメソッドがrunに取って代わる」なので、この訳文は逆の意味になっています（[実際の変更](https://github.com/rdkit/rdkit/pull/7085/files)を見てもvalidateが追加されてrunが削除されています）。日本語訳としては「`run`メソッドが`validate`に置き換えられ」のようにするのが自然だと思います。

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- 金属原子（実際にはデフォルトの価数が-1である任意の原子）は、結合を形成している場合、ラジカル電子数が0に設定されるようになりました。結合を持たない金属原子/イオンは、奇数の価電子を持つ場合も持たない場合も、引き続き1または0のラジカル数が割り当てられます。ケモインフォマティクスシステムでは、金属原子のスピン状態がどうあるべきかを一般的に答えることは不可能であるため、私たちはシンプルで簡単に
"assigned a radical count of either 1 or 0 if they do/do not have an odd number of valence electrons" は価電子数が奇数の時はラジカル電子数1、偶数の時はラジカル電子数0という意味だと思います。実際、[この文が追加されたコミット](https://github.com/rdkit/rdkit/commit/d1b9331a369d3ee0d824a04b3ba47f9913a110eb)のテストケースでは`[Mn+2]`と`[Mn]`のラジカル電子数が1、`[Mn+1]`と`[Mn-1]`のラジカル電子数が0になっています。この訳文ではその意味が反映されていないように感じるので、冗長ですが「価電子数が奇数の場合はラジカル電子数1、偶数の場合は0が割り当てられます」のように訳すほうが正確だと思います。

2024-08-12 09:07 UTC, n-yoshikawa commented on docs/release-2024-03-1.md
> +- 立体配座生成時のRMS剪定が、デフォルトで共役末端基を対称化するようになりました。これはパラメータ "symmetrizeConjugatedTerminalGroupsForPruning" で無効にできます。
- pruningの訳を枝刈りに統一するためにRMS pruningは「RMSによる枝刈り」とするのが良いのではないかと思いました。
- conformerは配座異性体またはコンフォーマーと訳すのが一般的です (cf. https://ja.wikipedia.org/wiki/%E7%AB%8B%E4%BD%93%E9%85%8D%E5%BA%A7)

2024-08-15 21:59 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- アトロピソマーをサポートする最初のバージョンが追加されました。これは将来のリリースで拡張される予定です。
ご指摘の通り修正しました。

2024-08-15 22:01 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- 立体配座生成のデフォルトを改善するために2つの変更が行われました。EmbedMolecule()関数とEmbedMultipleConfis()関数はデフォルトでETKDGv3を使用するようになり(以前はETKDGV1を使用していました)、配座剪定のためにRMSDを計算する際に重原子のみを考慮するようになりました(以前は水素原子も考慮されていました)。
ご指摘の通り修正しました。

2024-08-15 22:08 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- molブロックに由来する原子のラジカル電子数の計算方法が変更されました。`DOUBLET`としてマークされた`[CH]`のようなシステムには、3つのラジカル電子が割り当てられるようになりました。これはSMILESの値と一致しています。
ありがとうございます。ご指摘の通り修正いたしました。

2024-08-15 22:18 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- MolStandardizeのバリデーションクラスは、よりシンプルで一貫性のあるAPIを提供するためにリファクタリングされました。C++の実装では、`MolVSValidations`基底クラスが削除され、`ValidationMethod`に統合されました。その結果、MolVSに関連するサブクラス（つまり、`NoAtomValidation`、`FragmentValidation`、`N
失礼いたしました。取って代わるの意味を誤解していました。ご指摘の通り修正いたしました。

2024-08-15 22:31 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- 金属原子（実際にはデフォルトの価数が-1である任意の原子）は、結合を形成している場合、ラジカル電子数が0に設定されるようになりました。結合を持たない金属原子/イオンは、奇数の価電子を持つ場合も持たない場合も、引き続き1または0のラジカル数が割り当てられます。ケモインフォマティクスシステムでは、金属原子のスピン状態がどうあるべきかを一般的に答えることは不可能であるため、私たちはシンプルで簡単に
詳しくご確認いただきありがとうございます。ご指摘の通り修正いたしました。

2024-08-15 22:54 UTC, ItsukiMaeda commented on docs/release-2024-03-1.md
> +- 立体配座生成時のRMS剪定が、デフォルトで共役末端基を対称化するようになりました。これはパラメータ "symmetrizeConjugatedTerminalGroupsForPruning" で無効にできます。
ご指摘の通り修正いたしました。

2024-08-15 23:54 UTC, n-yoshikawa approved these changes

2024-08-15 23:54 UTC, merged

2024-08-15 23:55 UTC, n-yoshikawa commented
マージしました。ご協力いただきありがとうございました。